# Generated by Django 6.0.1 on 2026-01-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_criteria',
            field=models.CharField(default='No age limit', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_or_link',
            field=models.CharField(default='To be announced', max_length=200),
        ),
    ]
