# Generated by Django 6.0.1 on 2026-02-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_tag_remove_event_tags_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited participants', null=True),
        ),
    ]
