# Generated by Django 6.0.1 on 2026-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_cancellation_reason_event_event_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_state',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
