# Generated by Django 6.0.1 on 2026-02-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_event_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVisibilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_completed_after_days', models.PositiveIntegerField(default=7, help_text='Hide completed events from public list after N days')),
                ('hide_cancelled_after_days', models.PositiveIntegerField(default=0, help_text='Hide cancelled events from public list after N days (0 = hide immediately)')),
            ],
            options={
                'verbose_name': 'Event Visibility Settings',
                'verbose_name_plural': 'Event Visibility Settings',
            },
        ),
    ]
