# Generated by Django 6.0.1 on 2026-02-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventvisibilitysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvisibilitysettings',
            name='hide_cancelled_after_days',
            field=models.PositiveIntegerField(default=7, help_text='Hide cancelled events from public list after N days'),
        ),
    ]
