# Generated by Django 6.0.1 on 2026-01-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_created_at_community_rules_and_more'),
        ('events', '0004_tag_remove_event_tags_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.tag'),
        ),
    ]
